apiVersion: v1
kind: PersistentVolume
metadata:
  name: fastflows-volume
  labels:
    type: local
    app: fastflows
spec:
  storageClassName: manual
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /app/flows
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fastflows-volume-claim
  labels:
    app: fastflows
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastflows
spec:
  selector:
    matchLabels:
      app: fastflows
  replicas: 2
  template:
    metadata:
      labels:
        app: fastflows
    spec:
      initContainers:
        - name: check-orion-is-ready
          image: curlimages/curl
          command:
            [
              "sh",
              "-c",
              'while [ `curl -fsS http://orion:4200 --silent --output /dev/null"` -ne 200 ]; do sleep 2; done',
            ]
        - name: orion-queue
          image: prefecthq/prefect:2.4.1-python3.9
          command:
            [
              "sh",
              "-c",
              'prefect work-queue create default-queue; r=$?; [ "$r" -gt 0 ] && exit 0; exit 0',
            ]
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 4200
          env:
            - name: PREFECT_API_URL
              value: http://orion:4200/api
      containers:
        - name: main
          image: geobeyond/fastflows:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5010
          env:
            - name: PREFECT_URI
              value: http://orion:4200
            - name: FLOWS_HOME
              value: "/flows"
            - name: FASTFLOWS_PORT
              value: "5010"
          command: ["fastflows", "server"]
          volumeMounts:
            - mountPath: /flows
              name: fastflows-volume
      volumes:
        - name: fastflows-volume
          persistentVolumeClaim:
            claimName: fastflows-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: fastflows
  labels:
    app: fastflows
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5010
      targetPort: 5010
  selector:
    app: fastflows
