apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastflows-cluster
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: prefect.geo
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orion
                port:
                  number: 4200
    - host: fastflows.geo
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fastflows
                port:
                  number: 5010
