# up & run Prefect and FastFlows
# deploy flows from flows/ directory at the start
# or change on what ever you want

version: "3.9"

services:
  fastflows:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "5010:5010"
    volumes:
      - .:/app/src
      - ../flows:/app/flows
    image: fastflows
    restart: always
    environment:
      FLOWS_HOME: "flows"
      FLOWS_STORAGE_TYPE: "local"
      LOGGING__LEVEL: "DEBUG"
      PREFECT__API_TIMEOUT: 120
      PREFECT__STORAGE__BASE_PATH: "s3://test-bucket"
      PREFECT__STORAGE__BLOCK_NAME: "minio"
      PREFECT__STORAGE__BLOCK_TYPE: "remote-file-system"
      PREFECT__STORAGE__ENDPOINT_URL: "http://nginx:9000"
      PREFECT__STORAGE__KEY: "0xoznLEXV3JHiOKx"
      PREFECT__STORAGE__SECRET: "MmG3vfemCe5mpcxP66a1XvPnsIoXTlWs"
      PREFECT__URI: "http://prefect:4200"
      UVICORN__PORT: 5010
    depends_on:
      - prefect
      - postgres
  prefect:
    image: prefecthq/prefect:2.3.0-python3.9
    command: prefect orion start --host 0.0.0.0
    restart: always
    environment:
      - EXTRA_PIP_PACKAGES=s3fs
      - PREFECT_ORION_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/orion
    ports:
      - 4200:4200

  prefect_work_queue:
    image: prefecthq/prefect:2.3.0-python3.9
    entrypoint: prefect work-queue create default
    environment:
      - PREFECT_API_URL=http://prefect:4200/api
    restart: on-failure
    depends_on:
      - prefect
      - postgres

  prefect_agent:
    image: prefecthq/prefect:2.3.0-python3.9
    command: prefect agent start default
    environment:
      - EXTRA_PIP_PACKAGES=s3fs
      - PREFECT_API_URL=http://prefect:4200/api
    restart: on-failure
    depends_on:
      - prefect
      - postgres
      - prefect_work_queue
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orion
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
volumes:
  db:
    driver: local

networks:
  default:
    name: prefect-network
    external: true
